FROM openjdk:11

ADD imageFiles/logging.properties /logging.properties

RUN mkdir -p /build/install/wallet

ADD build/install/wallet /build/install/wallet

ARG builddate
ENV IMAGE_DATE=$builddate

CMD ["/bin/sleep","inf"]

EXPOSE 8000

################################################
# jove
RUN\
  apt-get update &&\
  apt-get install -y jove &&\
  apt-get clean