apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: wallet
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    name: wallet
spec:
  hostname: client
  subdomain: default-subdomain
  containers:
  - name: client
    image: gcr.io/grpc-testing/wallet-o11y-example:0.5
    imagePullPolicy: Always
    env:
    - name: GRPC_CONFIG_OBSERVABILITY_JSON
      value: "/o11y-config.json"
---
apiVersion: v1
kind: Pod
metadata:
  name: account-server
  labels:
    name: wallet
spec:
  hostname: account-server
  subdomain: default-subdomain
  containers:
  - name: account-server
    image: gcr.io/grpc-testing/wallet-o11y-example:0.5
    imagePullPolicy: Always
    command:
    - /account-server
    env:
    - name: GRPC_CONFIG_OBSERVABILITY_JSON
      value: "/o11y-config.json"
---
apiVersion: v1
kind: Pod
metadata:
  name: stats-server
  labels:
    name: wallet
spec:
  hostname: stats-server
  subdomain: default-subdomain
  containers:
  - name: stats-server
    image: gcr.io/grpc-testing/wallet-o11y-example:0.5
    imagePullPolicy: Always
    command:
    - /stats-server
    - --account_server=account-server.default-subdomain.default.svc.cluster.local:18883
    env:
    - name: GRPC_CONFIG_OBSERVABILITY_JSON
      value: "/o11y-config.json"
---
apiVersion: v1
kind: Pod
metadata:
  name: wallet-server
  labels:
    name: wallet
spec:
  hostname: wallet-server
  subdomain: default-subdomain
  containers:
  - name: wallet-server
    image: gcr.io/grpc-testing/wallet-o11y-example:0.5
    imagePullPolicy: Always
    command:
    - /wallet-server
    - --account_server=account-server.default-subdomain.default.svc.cluster.local:18883
    - --stats_server=stats-server.default-subdomain.default.svc.cluster.local:18882
    env:
    - name: GRPC_CONFIG_OBSERVABILITY_JSON
      value: "/o11y-config.json"
