apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
  - name: client
    image: gcr.io/grpc-testing/wallet-o11y-example:0.5
---
apiVersion: v1
kind: Pod
metadata:
  name: account-server
spec:
  containers:
  - name: account-server
    image: gcr.io/grpc-testing/wallet-o11y-example:0.5
---
apiVersion: v1
kind: Pod
metadata:
  name: stats-server
spec:
  containers:
  - name: stats-server
    image: gcr.io/grpc-testing/wallet-o11y-example:0.5
---
apiVersion: v1
kind: Pod
metadata:
  name: wallet-server
spec:
  containers:
  - name: wallet-server
    image: gcr.io/grpc-testing/wallet-o11y-example:0.5
